# Generated by Django 2.1.7 on 2019-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('custom_text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Selling', 'Selling'), ('Buying', 'Buying')], default='Selling', max_length=55)),
            ],
        ),
    ]
